# Generated by Django 3.2.6 on 2021-08-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField()),
                ( 'createdAt',models.DateTimeField(auto_now_add=True))
            ],
        ),
    ]
